config/routes.rb
Rails.application.routes.draw do

  get "schema_search"        => "schema_searches#search"
  get "schema_search/detail" => "schema_searches#detail"

  root "schema_searches#search"
end

app/models/account_executive.rb
class AccountExecutive < ApplicationRecord
  include SchemaSearchable
  set_searchable

  has_many :clients
end

app/models/admin.rb
class Admin < ApplicationRecord
  include SchemaSearchable
  set_searchable
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  include SchemaSearchable
  set_searchable
  
  belongs_to :account_executive
end

app/models/concerns/schema_searchable.rb
# https://github.com/ankane/searchkick#multiple-indices
# USAGE:
#   class User < ApplicationRecord
#     include SchemaSearchable
#     set_searchable
#   end
module SchemaSearchable
  extend ActiveSupport::Concern

  class_methods do

    # We add this class methods at the top of the class to bootstrap our search.
    def set_searchable
      searchkick
    end

    # Returns a string of underscored class_name.
    def underscored_class_name
      model_name.to_s.underscore
    end
  end

  included do

    # Allows us to control what data is indexed for searching.
    # By default, all the attributes and class_name_with_id are set, but
    # we can override this method to meet individual models' requirements.
    # NOTE: We need to reindex after making changes to the search attributes.
    def search_data
      merge = {
        # For filtering by class_name and for sorting by id
        class_name_with_id: self.underscored_class_name_with_id
      }
      attributes.merge(merge)
    end

    def underscored_class_name_with_id
      [
        self.class.underscored_class_name,
        self.id.to_s.rjust(5, '0')
      ].join("-")
    end

    def humanized_class_name_with_id
      "#{self.class.name.underscore.humanize} (ID: #{self.id})"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include SchemaSearchable
  set_searchable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SchemaSearchesHelper
end

app/controllers/schema_searches_controller.rb
class SchemaSearchesController < ApplicationController

  def search
    search = SchemaSearch.new(schema_search_params).search
    @results        = search[:results]
    @active_filters = search[:active_filters]
  end

  def detail
    @object = params[:type].classify.constantize.find(params[:id])
  end

  private def schema_search_params
    # TODO: make a whitelist.
    params.permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def set_title(title)
    provide(:title, title)
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title="")
    base_title = "Apartment showoff"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/schema_searches_helper.rb
module SchemaSearchesHelper
  
  # ---
  # Search meta
  # ---


  def total_count_text(results)
    "#{pluralize(results.try!(:total_count), "record")} found"
  end


  def q_text(filter_hash)
    if filter_hash["q"]&.present?
      filter_hash["q"]
    end
  end

  def class_name_text(filter_hash)
    if filter_hash["type"]&.present?
      filter_hash["type"]
    end
  end

  def sort_attribute_text(filter_hash)
    if filter_hash["sort_attribute"]&.present?
      filter_hash["sort_attribute"]
    end
  end

  def sort_order_text(filter_hash)
    if filter_hash["sort_order"]&.present?
      filter_hash["sort_order"]
    end
  end


  # ---
  # Filtering
  # ---


  def class_name_select_tag(params)
    options = SchemaSearch.searchable_class_names
    select_tag(
      "type",
      options_for_select(options, params[:type]),
      include_blank: true
    )
  end


  # ---
  # Sorting
  # ---


  def sort_attribute_select_tag(params)
    # NOTE: For some reason, sorting by id key does not work. Therefore, we use
    # joint strings of class_name and id for that purpose.
    options = {
      "class_name"  => "class_name_with_id",
      "created_at"  => "created_at",
      "updated_at"  => "updated_at",
    }
    select_tag(
      "sort_attribute",
      options_for_select(options, params[:sort_attribute]),
      include_blank: false
    )
  end

  def sort_order_select_tag(params)
    options = {
      "Ascending"  => "asc",
      "Descending" => "desc"
    }
    select_tag(
      "sort_order",
      options_for_select(options, params[:sort_order]),
      include_blank: false
    )
  end

end

app/views/layouts/_debug_box.html.slim
- if Rails.env.development?
  = debug(params)

app/views/layouts/_flash_message.html.slim
/ This is to render a Bootstrap 3 alert according to the specified alert type.
/ - Devise:    notice, alert
/ - Bootstrap: success, info, warning, danger

/ The flash_message_spacer
/ - used to push down the navbar when flash_message is displayed.
/ - necessary because the flash is fixed top and cannot push the navbar.

- flash.each do |type, message|
  - type = :success if notice
  - type = :danger  if alert
  div[class="alert alert-#{type} flash_message"]
    .container.text-centered
      .close[aria-hidden="true" data-dismiss="alert" type="button"]
        = fa_icon("times")
      .message = message
    .clearfix

javascript:

  $('.flash_message').on('mouseover', function() {
    setTimeout(function() {
      $('.close').click();
    }, 1000);
  })

app/views/layouts/_site_footer.html.slim
footer
  .container
    | Masatoshi Nishiguchi &middot;
    a [href="http://www.mnishiguchi.com/"] mnishiguchi.com

app/views/layouts/_site_header.html.slim
header

app/views/layouts/application.html.slim
doctype html
html
  head
    meta [content="text/html" charset="UTF-8", http-equiv="Content-Type"]
    meta [name="viewport" content="width=device-width, initial-scale=1.0"]

    title = full_title(yield(:title))

    link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" rel="stylesheet" /

    = stylesheet_link_tag 'application', media: 'all', \
                                            'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    /[if lt IE 9]
      script [src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"]

  body
    #flash_message
      = render 'layouts/flash_message'

    main.container
      = yield
    = render 'layouts/site_footer'

    script crossorigin="anonymous" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js"
    script crossorigin="anonymous" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js"

app/views/schema_search/_search_form.html.slim
= form_tag weather_readings_path, method: :get, remote:true do |f|

  .input-group
    input.form-control [
      type="search"
      id="q"
      name="q"
      placeholder="Search keyword..."
    ]

    .input-group-btn
      button.btn.btn-outline-success [type="submit"]
        = fa_icon("search")

    .input-group-btn
      /! Button trigger modal
      button.btn.btn-outline-secondary#advanced_search_fields_toggle
        = fa_icon("sliders")

  #advanced_search_fields
    = render "advanced_search_fields"

javascript:
  // Toggle advanced_search_fields.
  $('#advanced_search_fields_toggle').on('click', function() {
    $('#advanced_search_fields').toggle();
  });
  // Close advanced_search_fields on submit.
  $('button[type="submit"]').on('click', function() {
    $('#advanced_search_fields').hide();
  });

scss:
  // Hidden by default
  #advanced_search_fields {
    display: none;
  }

app/views/schema_search/_search_meta.html.slim
.navbar-text.search_meta
  span = pluralize(@weather_readings.try!(:total_count), "result")
  span = active_filters_text(@active_filters)

css:
  .search_meta > span {
    padding: 0 3px;
    font-size: .8rem;
  }

app/views/schema_search/index.html.slim
= set_title("Weather search")

.weather_readings_index
  .weather_readings_index__header
    #search_navbar.search_navbar
      = render "search_navbar"
  .weather_readings_index__content
    #search_result.search_result
      = render "search_result"

javascript:
  // // Toggle map.
  // $('#map_toggle').on('click', function() {
  //   $('#map').show();
  //   $('#search_result').hide();
  // })

  // Toggle search_result.
  $('#search_result_toggle').on('click', function() {
    $('#search_result').show();
  })

  // Close modal when clicking on submit.
  $('#advanced_search_submit').on('click', function() {
    $('#advanced_search_close').trigger("click");
  })

app/views/schema_search/index.js.erb
// http://guides.rubyonrails.org/working_with_javascript_in_rails.html#form-for
// http://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections

// Update the search result.
$('#search_result').html(
  '<%= j(render "search_result") %>'
);

// Update the search meta.
$('#search_meta').html(
  '<%= j(render "search_meta") %>'
);

// Update the webpage title.
$('title').html(
  '<%= j(weather_readings_title) %>'
);

app/views/schema_searches/_advanced_search_fields.html.slim
.card [style="min-width:60vw; margin-top: 1rem;"]
  ul.list-group
    li.list-group-item
      label> Type:
      = class_name_select_tag(params)
    li.list-group-item
      label> Sorting:
      = sort_attribute_select_tag(params)
      = sort_order_select_tag(params)

app/views/schema_searches/_search_form.html.slim
= form_tag(schema_search_path, method: :get, remote:true) do |f|

  .input-group
    input.form-control [
      type="search"
      id="q"
      name="q"
      placeholder="Search keyword..."
    ]

    .input-group-btn
      button.btn.btn-primary [type="submit"]
        = fa_icon("search")

    .input-group-btn
      /! Button trigger modal
      button.btn.btn-outline-secondary#advanced_search_fields_toggle
        = fa_icon("sliders")

  #advanced_search_fields
    = render "advanced_search_fields"

scss:
  // Hidden by default
  #advanced_search_fields {
    //display: none;
  }

javascript:
  // Toggle advanced_search_fields.
  $('#advanced_search_fields_toggle').on('click', function() {
    $('#advanced_search_fields').toggle();
  });
  // Close advanced_search_fields on submit.
  // $('button[type="submit"]').on('click', function() {
  //   $('#advanced_search_fields').hide();
  // });

app/views/schema_searches/_search_meta.html.slim
css:
  .search_meta span {
    margin: 0 0.5rem 0 0;
  }

.navbar-text.search_meta
  .h5
    span [style="display:block;"]
      = total_count_text(@results)
    span.tag.tag-pill.tag-primary
      = q_text(@active_filters)
    span.tag.tag-pill.tag-primary
      = class_name_text(@active_filters)

app/views/schema_searches/_search_navbar.html.slim
nav.navbar.navbar-light
  .row
    .col-sm-7
      #search_form
        = render "search_form"
      #search_meta
        = render "search_meta"
    .col-sm-5
      .btn-group
        button.btn.btn-outline-secondary#map_toggle [type="button"]
          = fa_icon("map-o")
        button.btn.btn-outline-secondary#search_result_toggle [type="button"]
          = fa_icon("th")

app/views/schema_searches/_search_result.html.slim
- if @results.empty?
  / http://v4-alpha.getbootstrap.com/components/card/
  .card
    .card-block
      p.card-text Nothing was found...
- else
  = paginate @results
  .card-columns
    - @results.each do |result|
      .card.card-outline-primary
        .card-header
          - text = result.humanized_class_name_with_id
          - type = result.class.name.underscore
          - id   = result.id
          = link_to text, schema_search_detail_path(type: type, id: id)
        .card-block
          - slice = ["id", "name", "created_at", "updated_at"]
          - result.attributes.slice(*slice).each do |k, v|
            p.card-text 
              small> = "#{k} :"
              small.text-muted.pull-right = v

app/views/schema_searches/detail.html.slim
= set_title(@object.humanized_class_name_with_id)

= link_to "Back to search", schema_search_path, class: "btn btn-secondary"

.card.card-outline-primary
  .card-block
    .card-title
      h4 = @object.humanized_class_name_with_id
    table.table.table-bordered
      tbody
        - @object.attributes.each do |k, v|
          - if k =~ /_id\z/
            tr 
              td = k 
              td 
                = link_to v, schema_search_detail_path(type: k.sub("_id", ""), id: v)
          - else
            tr 
              td = k
              td = v
          

app/views/schema_searches/index.html.slim
= set_title(schema_searches_title)

.weather_readings_index
  .weather_readings_index__header
    #search_navbar.search_navbar
      = render "search_navbar"
  .weather_readings_index__content
    #search_result.search_result
      = render "search_result"

javascript:
  // // Toggle map.
  // $('#map_toggle').on('click', function() {
  //   $('#map').show();
  //   $('#search_result').hide();
  // })

  // Toggle search_result.
  $('#search_result_toggle').on('click', function() {
    $('#search_result').show();
  })

  // Close modal when clicking on submit.
  $('#advanced_search_submit').on('click', function() {
    $('#advanced_search_close').trigger("click");
  })

app/views/schema_searches/index.js.erb
// http://guides.rubyonrails.org/working_with_javascript_in_rails.html#form-for
// http://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections

// Update the search result.
$('#search_result').html(
  '<%= j(render "search_result") %>'
);

// Update the search meta.
$('#search_meta').html(
  '<%= j(render "search_meta") %>'
);

// Update the webpage title.
$('title').html(
  '<%= j(schema_searches_title) %>'
);

app/views/schema_searches/search.html.slim
= set_title(total_count_text(@results))

.schema_search
  .schema_search__header
    #search_navbar.search_navbar
      = render "search_navbar"
.schema_search__content
  #search_result.search_result
    = render "search_result"

javascript:
  // // Toggle map.
  // $('#map_toggle').on('click', function() {
  //   $('#map').show();
  //   $('#search_result').hide();
  // })

  // Toggle search_result.
  $('#search_result_toggle').on('click', function() {
    $('#search_result').show();
  })

  // Close modal when clicking on submit.
  $('#advanced_search_submit').on('click', function() {
    $('#advanced_search_close').trigger("click");
  })

app/views/schema_searches/search.js.erb
// http://guides.rubyonrails.org/working_with_javascript_in_rails.html#form-for
// http://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections

// Update the search result.
$('#search_result').html(
  '<%= j(render "search_result") %>'
);

// Update the search meta.
$('#search_meta').html(
  '<%= j(render "search_meta") %>'
);

// Update the webpage title.
$('title').html(
  '<%= j(total_count_text(@results)) %>'
);